# See https://github.com/matthew-brett/multibuild

env:
  global:
    - REPO_DIR=pomegranate
    - BUILD_COMMIT=v0.8.1
    - TEST_DEPENDS="nose"
    - PLAT=x86_64
    - UNICODE_WIDTH=32
    - WHEELHOUSE_UPLOADER_USERNAME=scikit-image
    - secure: "V0ndHQXr8psDZH2uyMs8+4X/+dD05yt/itTvWtenUeurLDqXLakXFSc1qgZ5jYBUuosmC4QzOFCX36BSyYAKt9o2TIDPaW9jCrtX6DLCqPSGmryKqg8sTa6DA+qAb35ad6sK+AHqXNToIPyAyDJgjGo7dm+DcKWLHJWUS5cJTYUpLk33gWeH8Ldbu7UZEIHkgzWpSFEnAgN+EAXXh5IeutdkCwODAnpIYJ9uFAmfzUE6nYBruGFf0XHxnbVEGyWuKSmsUk7C6vbyJhZN983w2X4sKTxTx2HGHGJL3RBzVNtIoquoLq2IlTfpZwDmADPtw3ExA03vQki2ePEaPDuPZWTi/p7EtaXKPpQFIF+s3Z+/bsKvChwIhFxzMf5C2J24EcmqxKxOcNh2cqQ8xZHfXWLT4jVNRwT6GduwRHJZMmttxF6THhMDv8GTvXJQiNxZ5vnwLSHCYv61ircKta0KtfE+y9wHHzdGmzKNxVkPSoKrfkGHPUgSKMhsMlat490G6t6O/qhf9X8a5lEyRaFiyYxA6o2Nf2fpf4Q2DnhJR6n/1G2HSQYh/8zcnoVNIh606YuMuzeUnr9NcwyB9R3JUJ8WpqJFdIOhtG5oFi1yKq51ztHmWkVvhW30o5d+j4HUdY3AcBS34w37uF6gZU9Qr8FGshZjlhr4nLTwrG8wIUY="

language: python
python: 3.6
sudo: required
dist: trusty
services: docker


matrix:
  exclude:
  # Exclude the default Python 3.5 build
  - python: 3.6

  include:
  - os: linux
    env:
      - BUILD_DEPENDS="Cython numpy==1.8.0 scipy"
      - MB_PYTHON_VERSION=2.7

  - os: linux
    env:
      - BUILD_DEPENDS="Cython numpy==1.8.0 scipy"
      - MB_PYTHON_VERSION=3.4

  - os: linux
    env:
      - BUILD_DEPENDS="Cython numpy==1.8.0 scipy"
      - MB_PYTHON_VERSION=3.5
      
  - os: linux
    env:
      - BUILD_DEPENDS="Cython numpy==1.8.0 scipy"
      - MB_PYTHON_VERSION=3.6

  - os: osx
    language: generic
    env:
      - BUILD_DEPENDS="Cython numpy==1.9.0 scipy"
      - MB_PYTHON_VERSION=2.7

  - os: osx
    language: generic
    env:
      - BUILD_DEPENDS="Cython numpy==1.9.0 scipy"
      - MB_PYTHON_VERSION=3.4

  - os: osx
    language: generic
    env:
      - BUILD_DEPENDS="Cython numpy==1.9.0 scipy"
      - MB_PYTHON_VERSION=3.5
      
  - os: osx
    language: generic
    env:
      - BUILD_DEPENDS="Cython numpy==1.9.0 scipy"
      - MB_PYTHON_VERSION=3.6

before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

after_success:
    # Upload wheels to Rackspace
    - pip install wheelhouse-uploader
    # This uploads the wheels to a Rackspace container owned by the
    # scikit-learn team, available at http://wheels.scipy.org.  See
    # above for information on using this account or choosing another.
    - python -m wheelhouse_uploader upload --local-folder
      ${TRAVIS_BUILD_DIR}/wheelhouse/ --no-update-index wheels

